//
//  KeyPoint.swift
//  ShuoCore
//
//  Created by Justin Chow on 13/07/26.
//

// Domain entity: one key point, bound to exactly one `SpeechPatternComponent`. Content
// the transcript does not cover is represented by the literal `KeyPoint.absentText`
// ("-"), never by invented text — see `KeyPointNormalizer`.

import Foundation

/// One key point: the content extracted from a transcript for a single named component of
/// a speech pattern.
///
/// Key points always come in a complete set — one per component of the chosen pattern, in
/// component order, with `absentText` standing in wherever the transcript had nothing to
/// say. That invariant is established by `KeyPointNormalizer` and relied on by the UI, so
/// a caller can render slots positionally without checking for gaps.
public struct KeyPoint: Sendable, Identifiable, Equatable, Codable, Hashable {
    /// The text used when the transcript contains no content for this component.
    ///
    /// A literal placeholder rather than an optional or an empty string: the requirement
    /// is that an unaddressed component is *visibly* unaddressed, so the speaker can see
    /// which parts of the structure their draft is missing. That is much of the value of
    /// mapping onto a fixed structure in the first place.
    public static let absentText = "-"

    /// Identity is the component slug — key points are one-per-component within a set, so
    /// this is unique where it is used, and stable across regeneration in a way a fresh
    /// `UUID` would not be. Stability matters for SwiftUI list diffing when the user
    /// switches patterns and back.
    public var id: String { componentID }

    /// The `SpeechPatternComponent.id` this key point fills.
    public let componentID: String
    /// The component's display name, denormalized so a rendered key point needs no lookup
    /// back into the catalog.
    public let componentName: String
    /// Extracted content, or `absentText` when the transcript did not cover this
    /// component. Never empty.
    public var text: String
    /// Position within the key point set, matching `SpeechPatternComponent.order`.
    public let orderIndex: Int
    /// Ghost-text hint describing what belongs here, shown when the key point is absent.
    /// Derived from the component's `contains` list, not generated by the model.
    public let suggestion: String?

    public init(
        componentID: String,
        componentName: String,
        text: String,
        orderIndex: Int,
        suggestion: String? = nil
    ) {
        self.componentID = componentID
        self.componentName = componentName
        self.text = text
        self.orderIndex = orderIndex
        self.suggestion = suggestion
    }

    /// True when the transcript had no content for this component.
    public var isAbsent: Bool {
        text == Self.absentText
    }

    /// An empty key point for `component`, with ghost text derived from its `contains`
    /// hints. This is what `KeyPointNormalizer` substitutes for a slot the model left
    /// unfilled.
    public static func absent(for component: SpeechPatternComponent) -> KeyPoint {
        KeyPoint(
            componentID: component.id,
            componentName: component.name,
            text: absentText,
            orderIndex: component.order,
            suggestion: component.contains.isEmpty
                ? nil
                : component.contains.joined(separator: ", ")
        )
    }
}
