//
//  SpeechPattern.swift
//  ShuoCore
//
//  Created by Justin Chow on 13/07/26.
//

// Domain entity: one structural pattern from the fixed catalog — id, name, summary,
// purpose, and the ordered components key points map onto. Patterns are NOT generated by
// the model; `SpeechPatternCatalog` owns the closed set and the model only classifies
// against it. See `Docs/SPEECH_PATTERNS.md`.

import Foundation

/// A speech structure pattern: a named, ordered set of components a transcript can be
/// organized into.
///
/// Instances come from `SpeechPatternCatalog` and nowhere else. This is a deliberate
/// change from the earlier design in `Docs/ARCHITECTURE.md` §3.2.4, where the model
/// free-generated pattern names and summaries: a closed set is far more reliable on a
/// small on-device model, and — more importantly — a fixed component list is what lets
/// key points be mapped onto named slots at all.
///
/// `id` is a stable slug (`"inform.topical"`), not a `UUID`. It has to survive
/// persistence, key the per-pattern generation caches, and be the value the model returns
/// when classifying — a fresh random identifier per run could do none of those.
public struct SpeechPattern: Sendable, Identifiable, Equatable, Codable, Hashable {
    /// Stable catalog slug, namespaced by purpose — e.g. `"inform.topical"`,
    /// `"persuade.prep"`. Never change one once shipped; it is persisted on saved scripts.
    public let id: String
    /// Display name, e.g. "Topical (Categorical)".
    public let name: String
    /// One sentence on what the pattern organizes, shown on the pattern card.
    public let summary: String
    /// The purpose this catalog entry belongs to. Classification only ever considers
    /// patterns matching the purpose the user picked.
    public let purpose: SpeechPurpose
    /// Ordered component slots. Guaranteed non-empty and sorted by
    /// `SpeechPatternComponent.order` for every catalog entry.
    public let components: [SpeechPatternComponent]
    /// Provenance, where the source material cited one. Not surfaced in v1's UI.
    public let sourceNote: String?

    public init(
        id: String,
        name: String,
        summary: String,
        purpose: SpeechPurpose,
        components: [SpeechPatternComponent],
        sourceNote: String? = nil
    ) {
        self.id = id
        self.name = name
        self.summary = summary
        self.purpose = purpose
        self.components = components.sorted { $0.order < $1.order }
        self.sourceNote = sourceNote
    }

    /// The component with the given id, or nil when the id is not part of this pattern.
    public func component(id componentID: String) -> SpeechPatternComponent? {
        components.first { $0.id == componentID }
    }

    /// Case- and punctuation-insensitive lookup by display name.
    ///
    /// The model is asked to label each extracted passage with a component *name* rather
    /// than a slug — names are natural language it handles far more reliably than opaque
    /// identifiers. This is the matching step that turns that label back into a component.
    public func component(matchingName rawName: String) -> SpeechPatternComponent? {
        let needle = Self.normalizeForMatching(rawName)
        guard !needle.isEmpty else { return nil }
        return components.first { Self.normalizeForMatching($0.name) == needle }
    }

    /// Lowercases and strips everything but alphanumerics, so "Category 1", "category 1"
    /// and "Category  1." all collapse to the same key.
    static func normalizeForMatching(_ value: String) -> String {
        value.lowercased().filter { $0.isLetter || $0.isNumber }
    }
}
